
package co.unicauca.microkernel.presentation;

import co.unicauca.microkernel.business.MeasureService;
import co.unicauca.microkernel.business.ServiceModel;
import co.unicauca.microkernel.common.entities.Measure;
import co.unicauca.microkernel.common.entities.Product;
import co.unicauca.microkernel.infra.Publisher;
import javax.swing.JOptionPane;
import com.google.gson.Gson;

public class GUIAddProductViewController extends javax.swing.JFrame {
    private final ServiceModel service;
    private final MeasureService measureService;
    Publisher publisher;
    /**
     * Creates new form AddProduct
     * @param service
     */
    public GUIAddProductViewController(ServiceModel service) {
        initComponents();
        this.service = service;
        this.publisher = new Publisher();
        measureService = new MeasureService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBk = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblDiametro = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblTMedicion = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtDiametro = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtTMedicion = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblCode = new javax.swing.JLabel();
        txtCodeItem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("NUEVO PRODUCTO - SISTEMA DE MEDICION");

        lblPeso.setText("Peso del producto");

        lblDiametro.setText("Diametro del producto");

        lblAltura.setText("Altura del producto");

        lblTMedicion.setText("Tiempo de medicion");

        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-product.png")));
        btnAddProduct.setText("Agregar");
        btnAddProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-product.png")));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblID.setText("ID del producto");

        lblCode.setText("Codigo del producto");

        javax.swing.GroupLayout JPanelBkLayout = new javax.swing.GroupLayout(JPanelBk);
        JPanelBk.setLayout(JPanelBkLayout);
        JPanelBkLayout.setHorizontalGroup(
            JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelBkLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(64, 64, 64))
            .addGroup(JPanelBkLayout.createSequentialGroup()
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBkLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDiametro)
                            .addComponent(lblTMedicion)
                            .addComponent(lblAltura)
                            .addComponent(lblPeso)
                            .addComponent(lblID)))
                    .addGroup(JPanelBkLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelBkLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPeso)
                        .addComponent(txtDiametro)
                        .addComponent(txtAltura)
                        .addComponent(txtTMedicion)
                        .addComponent(txtID)
                        .addComponent(txtCodeItem, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelBkLayout.setVerticalGroup(
            JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBkLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiametro)
                    .addComponent(txtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTMedicion)
                    .addComponent(txtTMedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode)
                    .addComponent(txtCodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanelBkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProduct)
                    .addComponent(btnBuscar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearFields(){
        txtAltura.setText("");
        txtCodeItem.setText("");
        txtDiametro.setText("");
        txtID.setText("");
        txtPeso.setText("");
        txtTMedicion.setText("");
    }
    
    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        
        int id = Integer.parseInt(txtID.getText());
        double peso = Double.parseDouble(txtPeso.getText());
        double diametro = Double.parseDouble(txtDiametro.getText());
        double altura = Double.parseDouble(txtAltura.getText());
        int tiempo_medicion = Integer.parseInt(txtTMedicion.getText());
        String codigo_producto = txtCodeItem.getText();
   
        Product newProduct = new Product(id, peso, diametro, altura);
        Measure measurementEntity = new Measure(/*newProduct, tiempo_medicion, codigo_producto*/);
        measurementEntity.setProduct(newProduct);
        measurementEntity.setEstado("En medicion");
        measurementEntity.setTiempo(tiempo_medicion);
        measurementEntity.setItemCode(codigo_producto);
        try {
            boolean medicion = measureService.calculateMeasureCost(measurementEntity);
            if(medicion){
                JOptionPane.showMessageDialog(null, "La medición fue exitosa.");
                measurementEntity.setEstado("Aceptable");
                service.addMeasure(measurementEntity);
                
                Gson gson = new Gson();
                String msgJson = gson.toJson(measurementEntity);
                publisher.publish(msgJson);
                
                clearFields();
            }else{
                JOptionPane.showMessageDialog(null, "La medición indica que la lata esta defectuosa.");
                measurementEntity.setEstado("Defectuoso");
                service.addMeasure(measurementEntity);
                
                Gson gson = new Gson();
                String msgJson = gson.toJson(measurementEntity);
                publisher.publish(msgJson);
                
                clearFields();
            }
            
        } catch (Exception exception) {
            System.out.println("No fue posible medir el item. " + exception.getMessage());
        }
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        Measure mesure = service.findMeasure(Integer.parseInt(txtID.getText()));
        if(mesure!=null){
            txtID.setText(Integer.toString(mesure.getProduct().getProductId()));
            txtPeso.setText(Double.toString(mesure.getProduct().getWeight()));
            txtDiametro.setText(Double.toString(mesure.getProduct().getDiameter()));
            txtAltura.setText(Double.toString(mesure.getProduct().getHeight()));
            txtTMedicion.setText(Integer.toString(mesure.getTiempo()));
            txtCodeItem.setText(mesure.getItemCode());
        }else{
            JOptionPane.showMessageDialog(null, "No se ha medido el item.");   
            clearFields();
        }        
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBk;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDiametro;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTMedicion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtCodeItem;
    private javax.swing.JTextField txtDiametro;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTMedicion;
    // End of variables declaration//GEN-END:variables
}
